application: twittergo-example
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
  expiration: "30d"

- url: /admin/?.*
  script: _go_app
  login: admin
  secure: always

- url: /.*
  script: _go_app
